name: Issue Workflow
on: 
  issues: 
    types: [opened, edited]
jobs:
  see-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Output event Details
        run: |
          echo "A new issue was opened. Title: ${{ github.event.issue.title }}"
          echo "See the issue in: ${{ github.event.issue.html_url }}"

